boostcampwm-2022/iOS09-burstcamp

Eoljuga/Eoljuga.xcodeproj/project.pbxproj, Eoljuga/Eoljuga/Auth/LoginViewController.swift, Eoljuga/Eoljuga/Coordinator/AppCoordinator.swift, Eoljuga/Eoljuga/Coordinator/AuthCoordinator.swift, Eoljuga/Eoljuga/Coordinator/Coordinator.swift, Eoljuga/Eoljuga/Coordinator/TabBarCoordinator.swift, Eoljuga/Eoljuga/Coordinator/TabCoordinator.swift, Eoljuga/Eoljuga/SceneDelegate.swift, Eoljuga/Eoljuga/Tab/Bookmark/BookmarkViewController.swift, Eoljuga/Eoljuga/Tab/Home/HomeViewController.swift, Eoljuga/Eoljuga/Tab/MyPage/MyPageViewController.swift
- #6 
- Coordinator 패턴 적용을 위해 뼈대만 작성
빠른 리뷰 부탁드려요
- 추후 Combine 으로 수정
- 피그마에 그림 정리
=> [Feature] coordinator 패턴 기초 구현

Eoljuga/Eoljuga/Scene/Common/View/DefaultBadgeLabel.swift, Eoljuga/Eoljuga/Scene/Common/View/DefaultProfileImageView.swift, Eoljuga/Eoljuga/Scene/Tab/MyPage/View/MyPageView.swift, Eoljuga/Eoljuga/Scene/Tab/MyPage/ViewController/MyPageViewController.swift, Eoljuga/Eoljuga/Util/Constant/Constant.swift
- close #56 
- constraint가 앱 화면에서 보니 조금 어색해서.. 추후에 고칠 예정입니다.
- CollectionView List Layout과 CellAccessory를 사용해서 구현했습니다.
- View만 구현
- 레퍼런스 이슈 참조
=> [마이페이지 설정] CollectionView List 사용 #56

Eoljuga/Eoljuga.xcodeproj/project.pbxproj, Eoljuga/Eoljuga/Model/Domain.swift, Eoljuga/Eoljuga/Model/UserDTO.swift, Eoljuga/Eoljuga/Service/FireStoreService.swift, Eoljuga/Eoljuga/Service/URLSessionService.swift, Eoljuga/Eoljuga/Util/Constant/FireStoreConfiguration.swift, Eoljuga/Eoljuga/Util/Constant/HTTPMethod.swift, Eoljuga/Eoljuga/Util/Constant/NetworkError.swift, Eoljuga/Eoljuga/Util/Query/FireStoreValues.swift, Eoljuga/Eoljuga/Util/Query/Query.swift, Eoljuga/Eoljuga/Util/Query/UserQuery.swift
- close #57 
- #58 
- 이슈 참고
- 정리해서 대면 코드리뷰 요청하겠습니다.
- 프로젝트 파일을 많이~ 건드려서 충돌날 가능성이 높습니다.
- 파일 위치도 같이 봐주시면 좋겠습니다.
- 아직 분리할 부분이 많은 코드라 `FireStoreService`의 url 생성하는 부분과 request 생성하는 부분은 조금 더 정리가 필요합니다.
- User `save`와 `fetch`만 우선 만들었습니다. (Combine)
- 좀 더 나은 레퍼런스가 있다면 추천해주세욥~
참조
- [Routinus](https://github.com/boostcampwm-2021/iOS03-Routinus)
- [MateRunner](https://github.com/boostcampwm-2021/iOS06-MateRunner)
=> [네트워크, FireStore] URLSession + FireStore rest

Eoljuga/Eoljuga/Scene/Tab/MyPage/View/OpenSourceLicenseView.swift
=> [마이페이지] 코드리뷰 반영

Eoljuga/Eoljuga/Coordinator/AuthCoordinator.swift, Eoljuga/Eoljuga/Scene/Auth/LogIn/LogInView.swift, Eoljuga/Eoljuga/Scene/Auth/LogIn/LoginViewController.swift, Eoljuga/Eoljuga/Scene/Auth/SignUp/Blog/SignUpBlogView.swift, Eoljuga/Eoljuga/Scene/Auth/SignUp/Blog/SignUpBlogViewController.swift, Eoljuga/Eoljuga/Scene/Auth/SignUp/CamperID/SignUpCamperIDView.swift, Eoljuga/Eoljuga/Scene/Auth/SignUp/CamperID/SignUpCamperIDViewController.swift, Eoljuga/Eoljuga/Scene/Auth/SignUp/Domain/SighUpDomainView.swift, Eoljuga/Eoljuga/Scene/Auth/SignUp/Domain/SignUpDomainViewController.swift, Eoljuga/Eoljuga/Scene/Auth/SignUp/SignUpViewModel.swift, Eoljuga/Eoljuga/Util/Constant/Constant.swift
=> feat: blog 입력 화면 만들기

Eoljuga/Eoljuga.xcodeproj/project.pbxproj, Eoljuga/Eoljuga/App/SceneDelegate.swift, Eoljuga/Eoljuga/Coordinator/TabBarCoordinator.swift, Eoljuga/Eoljuga/Model/Appearance.swift, Eoljuga/Eoljuga/Resource/Colors.xcassets/background.colorset/Contents.json, Eoljuga/Eoljuga/Resource/Colors.xcassets/black.colorset/Contents.json, Eoljuga/Eoljuga/Resource/Generated/Colors+Generated.swift, Eoljuga/Eoljuga/Scene/Tab/MyPage/View/MyPageProfileView.swift, Eoljuga/Eoljuga/Scene/Tab/MyPage/View/MyPageView.swift, Eoljuga/Eoljuga/Scene/Tab/MyPage/View/OpenSourceLicenseView.swift, Eoljuga/Eoljuga/Scene/Tab/MyPage/ViewController/MyPageViewController.swift, Eoljuga/Eoljuga/Scene/Tab/MyPage/ViewModel/MyPageViewModel.swift, Eoljuga/Eoljuga/Service/DarkmodeManager.swift, Eoljuga/Eoljuga/Service/UserDefaultsManager.swift, Eoljuga/Eoljuga/Util/Extension/UIColor+ColorSet.swift, Eoljuga/Eoljuga/Util/Extension/UIControl+Combine.swift, Eoljuga/Eoljuga/Util/Extension/UINavigationController+configure.swift
- close #83
- ColorSet
- `UIColor.background` => 다크모드 대응 background 컬러입니다.
- `UIColor.dynamicBlack, UIColor.dynamicWhite` => 다크모드 여부에 따라 바뀌는 black, white 컬러입니다.
- 각자 화면에서 컬러 업데이트 부탁드립니다!
MypageViewModel 에서 Input에서 다크모드 스위치 바뀔 때마다 업데이트하고,  
Output에서 UserDefault에 저장된 다크모드 값으로 스위치 초기값 설정해줬습니다.  
이슈참조
=> [다크모드] 설정 및 네비게이션, 탭바, 마이페이지 다크모드 대응

Eoljuga/Eoljuga/Scene/Tab/Home/View/HomeView.swift, Eoljuga/Eoljuga/Scene/Tab/Home/View/RecommendFeedSection/RecommendFeedCell.swift, Eoljuga/Eoljuga/Scene/Tab/Home/ViewController/HomeViewController.swift, Eoljuga/Eoljuga/Util/Constant/Constant.swift
- close #63 
- close #62
- visibleItemsInvalidationHandler를 사용해 추천 피드 무한 스크롤을 구현했습니다.
- 동작 영상
https://user-images.githubusercontent.com/71776532/203270544-66c7165c-e872-4d78-a93b-449d5c4fb897.mp4
- 설명을 위해 흐름을 작성해봤습니다. 아직 작성 중이라 조금만 기다려 주세요.
- https://sseungmn.notion.site/Compositional-Layout-Carousel-View-b0821c1e4c7e46b795942822acb24c7e
=> [홈] 추천 피드 - 무한 스크롤 (carousel View)

Eoljuga/Eoljuga.xcodeproj/project.pbxproj, Eoljuga/Eoljuga/Model/CellIndexPath.swift, Eoljuga/Eoljuga/Scene/Common/View/DefaultBadgeLabel.swift, Eoljuga/Eoljuga/Scene/Common/View/DefaultImageLabel.swift, Eoljuga/Eoljuga/Scene/Common/View/DefaultProfileImageView.swift, Eoljuga/Eoljuga/Scene/Common/View/DefaultTextField.swift, Eoljuga/Eoljuga/Scene/Tab/MyPage/View/MyPageEditView.swift, Eoljuga/Eoljuga/Scene/Tab/MyPage/View/MyPageProfileView.swift, Eoljuga/Eoljuga/Scene/Tab/MyPage/View/OpenSourceLicenseView.swift, Eoljuga/Eoljuga/Scene/Tab/MyPage/View/SettingCell.swift, Eoljuga/Eoljuga/Scene/Tab/MyPage/View/SettingSection.swift, Eoljuga/Eoljuga/Scene/Tab/MyPage/ViewController/MyPageViewController.swift, Eoljuga/Eoljuga/Util/Constant/Constant.swift, Eoljuga/Eoljuga/Util/Extension/UIStackView+addArrangedSubviews.swift
=> [마이페이지] 수정 view

burstcamp/burstcamp/Coordinator/AppCoordinator.swift, burstcamp/burstcamp/Coordinator/TabBarCoordinator.swift, burstcamp/burstcamp/Util/Extension/UI/UINavigationController+configure.swift, burstcamp/burstcamp/Util/Extension/UIViewController+ToastMessage.swift
=> [공통] 네비게이션, 탭바 배경색 iOS 15 이상 대응

burstcamp/burstcamp.xcodeproj/project.pbxproj, burstcamp/burstcamp/Model/Blog.swift, burstcamp/burstcamp/Model/BlogDTO.swift, burstcamp/burstcamp/Model/FireStoreResult.swift, burstcamp/burstcamp/Model/User.swift, burstcamp/burstcamp/Model/UserDTO.swift, burstcamp/burstcamp/Scene/Tab/MyPage/View/MyPageEditView.swift, burstcamp/burstcamp/Scene/Tab/MyPage/ViewController/MyPageViewController.swift, burstcamp/burstcamp/Scene/Tab/MyPage/ViewModel/MyPageEditViewModel.swift, burstcamp/burstcamp/Service/FireStoreService.swift, burstcamp/burstcamp/Service/LogInManager.swift, burstcamp/burstcamp/Service/URLSessionService.swift, burstcamp/burstcamp/Util/Constant/FireStoreConfiguration.swift, burstcamp/burstcamp/Util/Constant/HTTPHeader.swift, burstcamp/burstcamp/Util/Constant/NetworkError.swift, burstcamp/burstcamp/Util/Query/BlogQuery.swift, burstcamp/burstcamp/Util/Query/UserQuery.swift
- #58 
- URLSession 리팩토링하고 user save, update, fetch 쿼리 추가했습니다.
=> [Firebase] URLSessionService 리팩토링

burstcamp/burstcamp/Service/FireStoreService.swift, burstcamp/burstcamp/Service/LogInManager.swift, burstcamp/burstcamp/Util/Constant/HTTPHeader.swift, burstcamp/burstcamp/Util/Query/BlogQuery.swift
=> fix: Lint 오류 수정

burstcamp/burstcamp/Coordinator/AuthCoordinator.swift, burstcamp/burstcamp/Coordinator/AuthCoordinatorEvent.swift, burstcamp/burstcamp/Scene/Auth/LogIn/LogInView.swift, burstcamp/burstcamp/Scene/Auth/LogIn/LoginViewController.swift, burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewController.swift, burstcamp/burstcamp/Scene/Auth/SignUp/CamperID/SignUpCamperIDViewController.swift, burstcamp/burstcamp/Service/LogInManager.swift
close #104 
캠퍼여부, 회원가입 여부에 따른 화면 전환 처리를 위한 combine 적용
=> feat: loginflow에 combine 적용

Firebase-Functions/functions/index.js, Firebase-Functions/functions/service/feedAPI.js, Firebase-Functions/functions/util.js
하늘이님의 초당 5번의 요청으로
blog 제목을 가져오는 메서드를 빠르게 만들어봤습니다.
=> fetchBlogTitle API 만들었어요

burstcamp/burstcamp.xcodeproj/project.pbxproj, burstcamp/burstcamp/Model/User.swift, burstcamp/burstcamp/Scene/Tab/MyPage/ViewController/MyPageViewController.swift, burstcamp/burstcamp/Scene/Tab/MyPage/ViewModel/MyPageEditViewModel.swift, burstcamp/burstcamp/Service/FirestoreUser.swift, burstcamp/burstcamp/Service/UserManager.swift, burstcamp/burstcamp/Util/Validation/Validation.swift
=> hotfix: project file

burstcamp/burstcamp/Model/Domain.swift, burstcamp/burstcamp/Scene/Tab/Home/View/RecommendFeedSection/RecommendFeedCell.swift, burstcamp/burstcamp/Scene/Tab/Home/View/RecommendFeedSection/RecommendFeedUserView.swift, burstcamp/burstcamp/Scene/Tab/Home/ViewController/HomeViewController.swift, burstcamp/burstcamp/Scene/Tab/Home/ViewModel/HomeViewModel.swift
- close #53
- 승민님의 코드에 영감을 받아 taskGroup을 사용해 recommend Feed를 받아옵니다. 코드가 괜찮은 거 같으면 기존 코드도 바로 수정하겠습니다.
- 도메인에 따라 추천 피드 배경색이 변경됩니다.
- 현재 추천피드, 노말 피드 응답 이후 각각 reloadData를 한 번씩 해줌 -> 두 개다 도착했을 때 한 번에 할 수 있도록 수정 필요
- refresh하고 추천피드가 새로고침되는데 이전 프로필 이미지가 남아있는 버그가 있음 -> 수정 필요
=> [홈] taskGroup을 사용해 추천피드 받아오기

burstcamp/burstcamp/Scene/Common/View/DefaultToggleButton.swift, burstcamp/burstcamp/Scene/Tab/Detail/View/FeedDetailView.swift, burstcamp/burstcamp/Scene/Tab/Detail/ViewController/FeedDetailViewController.swift, burstcamp/burstcamp/Scene/Tab/Detail/ViewModel/FeedDetailViewModel.swift
- close #139 
이슈 보시면 됩니다.
플로우 차트에 맞게 작성되었는지
=> Feed detail 스크랩 버튼 로직 구현

burstcamp/burstcamp.xcodeproj/project.pbxproj, burstcamp/burstcamp/Coordinator/AuthCoordinator.swift, burstcamp/burstcamp/Coordinator/AuthCoordinatorEvent.swift, burstcamp/burstcamp/Scene/Auth/LogIn/LogInView.swift, burstcamp/burstcamp/Scene/Auth/LogIn/LogInViewModel.swift, burstcamp/burstcamp/Scene/Auth/LogIn/LoginViewController.swift, burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewController.swift, burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewModel.swift, burstcamp/burstcamp/Scene/Auth/SignUp/CamperID/SignUpCamperIDViewController.swift, burstcamp/burstcamp/Scene/Auth/SignUp/CamperID/SignUpCamperIDViewModel.swift, burstcamp/burstcamp/Scene/Auth/SignUp/Domain/SignUpDomainViewController.swift, burstcamp/burstcamp/Scene/Auth/SignUp/Domain/SignUpDomainViewModel.swift, burstcamp/burstcamp/Scene/Auth/SignUp/SignUpViewModel.swift, burstcamp/burstcamp/Service/LogInManager.swift, burstcamp/burstcamp/Service/UserManager.swift, burstcamp/burstcamp/Util/Extension/UI/UIViewController+.swift, burstcamp/burstcamp/Util/Extension/UI/UIViewController+ToastMessage.swift
=> [공통] 블로그 주소 검증 & alert

burstcamp/burstcamp/App/SceneDelegate.swift, burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewModel.swift, burstcamp/burstcamp/Service/LogInManager.swift, burstcamp/burstcamp/Service/UserManager.swift
=> class명 변경된 부분 수정

burstcamp/burstcamp.xcodeproj/project.pbxproj, burstcamp/burstcamp/App/SceneDelegate.swift, burstcamp/burstcamp/Scene/Common/View/DefaultImageLabel.swift, burstcamp/burstcamp/Scene/Common/View/DefaultProfileImageView.swift, burstcamp/burstcamp/Scene/Common/View/DefaultTextField.swift, burstcamp/burstcamp/Scene/Tab/MyPage/View/MyPageEditView.swift, burstcamp/burstcamp/Scene/Tab/MyPage/View/MyPageProfileView.swift, burstcamp/burstcamp/Scene/Tab/MyPage/View/MyPageView.swift, burstcamp/burstcamp/Scene/Tab/MyPage/ViewController/MyPageEditViewController.swift, burstcamp/burstcamp/Scene/Tab/MyPage/ViewController/MyPageViewController.swift, burstcamp/burstcamp/Scene/Tab/MyPage/ViewModel/MyPageEditViewModel.swift, burstcamp/burstcamp/Scene/Tab/MyPage/ViewModel/MyPageViewModel.swift, burstcamp/burstcamp/Service/FireFunctionsManager.swift, burstcamp/burstcamp/Service/FireStorageService.swift, burstcamp/burstcamp/Service/FirestoreUser.swift, burstcamp/burstcamp/Service/UserManager.swift, burstcamp/burstcamp/Util/Constant/Alert.swift, burstcamp/burstcamp/Util/Constant/MyPageEditValidationResult.swift, burstcamp/burstcamp/Util/Error/FireStorageError.swift, burstcamp/burstcamp/Util/Extension/UI/UIViewController+.swift
- #27 
- #28 
- #29 
- close #30 
이슈
- 이미지 로드 성능 개선 예정입니다.
- 유저 정보 처리는 키체인이 추가될 예정입니다. (현재는 전부 서버에서 불러옵니다.)
=> [마이페이지, 유저처리] 리팩토링 및 기능

burstcamp/burstcamp.xcodeproj/project.pbxproj, burstcamp/burstcamp/Model/Domain.swift, burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogView.swift, burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewController.swift, burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewModel.swift, burstcamp/burstcamp/Scene/Auth/SignUp/CamperID/SignUpCamperIDViewModel.swift, burstcamp/burstcamp/Scene/Auth/SignUp/Domain/SignUpDomainViewController.swift, burstcamp/burstcamp/Scene/Auth/SignUp/Domain/SignUpDomainViewModel.swift, burstcamp/burstcamp/Service/LogInManager.swift, burstcamp/burstcamp/Util/Extension/UI/UIViewController+.swift
- close #149 
- close #150 
github 로그인 후 앱이 죽어버리는 현상이 없는지
firebase path오류가 안뜨는지
=> [에러처리] 깃헙 로그인 시 앱이 죽어버리던 오류 해결

burstcamp/burstcamp/Scene/Tab/Home/View/RecommendFeedSection/RecommendFeedCell.swift
- Merge conflict 해결 과정 중 프로퍼티 이름 수정으로 인한 에러 발생
- 빠른 APPROVE 부탁드립니다.
- Merge 전 빌드를 생활화 합시다.
=> [Hotfix] Feed 모델 프로퍼티 바뀐거 수정

burstcamp/burstcamp/Scene/Auth/LogIn/LoginViewController.swift, burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewModel.swift, burstcamp/burstcamp/Service/LogInManager.swift
close #154 
domain이 두번 푸시되는 상황에서 어떤 로직을 탔는지 확인하기 위한 print문을 추가했습니다
테스트 해보시다가 두번 호출되는 상황의 콘솔 내용 알려주세요
=> [테스트] coordinator함수 호출 부 print문 추가

burstcamp/burstcamp/Model/Domain.swift, burstcamp/burstcamp/Scene/Common/View/DefaultImageLabel.swift, burstcamp/burstcamp/Scene/Common/View/DefaultTextField.swift, burstcamp/burstcamp/Scene/Tab/MyPage/View/MyPageEditView.swift, burstcamp/burstcamp/Scene/Tab/MyPage/View/MyPageView.swift, burstcamp/burstcamp/Scene/Tab/MyPage/ViewController/MyPageViewController.swift, burstcamp/burstcamp/Scene/Tab/MyPage/ViewModel/MyPageEditViewModel.swift, burstcamp/burstcamp/Util/Constant/MyPageEditValidationResult.swift, burstcamp/burstcamp/Util/Extension/UI/UIViewController+.swift, burstcamp/burstcamp/Util/Validation/Validation.swift
=> [마이페이지] 리팩토링

burstcamp/burstcamp.xcodeproj/project.pbxproj, burstcamp/burstcamp/App/AppDelegate.swift, burstcamp/burstcamp/Coordinator/AppCoordinator.swift, burstcamp/burstcamp/Service/FireStorageService.swift, burstcamp/burstcamp/Service/KeyChainManager.swift, burstcamp/burstcamp/Service/UserManager.swift
=> [유저 정보처리] 키체인 추가

burstcamp/burstcamp/Model/Domain.swift, burstcamp/burstcamp/Scene/Tab/MyPage/ViewModel/MyPageEditViewModel.swift, burstcamp/burstcamp/Scene/Tab/ScrapPage/ViewModel/ScrapPageViewModel.swift
=> [오류수정] hotfix

burstcamp/burstcamp/Model/User.swift, burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewModel.swift, burstcamp/burstcamp/Service/FirestoreUser.swift
=> [refactor] Date -> timeStamp 변경

burstcamp/burstcamp/Scene/Auth/LogIn/LogInViewModel.swift, burstcamp/burstcamp/Scene/Auth/LogIn/LoginViewController.swift, burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewController.swift, burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewModel.swift
=> [회원가입] throttle, blogTitle 확인 Alert 추가

burstcamp/burstcamp/Scene/Auth/LogIn/LogInView.swift, burstcamp/burstcamp/Scene/Auth/LogIn/LogInViewModel.swift, burstcamp/burstcamp/Scene/Auth/LogIn/LoginViewController.swift, burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogView.swift, burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewController.swift, burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewModel.swift
=> feat: indicator 추가

Firebase-Functions/functions/index.js, Firebase-Functions/functions/package-lock.json, Firebase-Functions/functions/package.json, Firebase-Functions/functions/service/apnsManager.js, Firebase-Functions/functions/service/firestoreManager.js, burstcamp/burstcamp/App/AppDelegate.swift, burstcamp/burstcamp/Coordinator/App/AppCoordinator.swift, burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewController.swift, burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewModel.swift, burstcamp/burstcamp/Scene/Tab/Home/ViewController/HomeViewController.swift, burstcamp/burstcamp/Scene/Tab/MyPage/View/MyPageView.swift, burstcamp/burstcamp/Scene/Tab/MyPage/View/SettingCell.swift, burstcamp/burstcamp/Scene/Tab/MyPage/ViewController/MyPageViewController.swift, burstcamp/burstcamp/Scene/Tab/MyPage/ViewModel/MyPageViewModel.swift, burstcamp/burstcamp/Service/FirestoreFCMToken.swift, burstcamp/burstcamp/Service/UserDefaultsManager.swift, burstcamp/burstcamp/Service/UserManager.swift
- close #27 
- close #28 
- 기훈님의 탈퇴로직 변경 후 다시 탈퇴로직을 테스트 할 예정입니다.!
- 현재 탈퇴시 유저정보는 User Singleton 정보 삭제, 키체인 정보 삭제합니다.
- 앱 종료시 키체인에 유저 정보를 저장하는데서 주의점이 하나 있는데..ㅇㅅㅇ
- 시뮬레이터 안에서 앱을 종료하면 저장이되고, 엑스코드에서 정지로 앱을 멈추면 키체인 정보가 저장이 안되더라구요,,
- 노드 주거
- 실기기로 테스트하는게 좋을 것 같습니다. 
- 오후 12시 16분에 알림 설정
---
- 원래 앱 켰을 때 푸시알림 권한을 물어봤는데 홈화면에 진입시로 변경하였습니다.
- 두가지 오류가..ㅠㅠㅠ
- foreground 알림 안옴
- 알림이 두번 옴
- 낼 출근해서 고쳐보겠으비낟.
- 테스트 환경에서는 주석이 있는게 좋을 것 같아서 주석을 남겨두었습니다.
- 코디네이터가 동작을..?
=> [탈퇴, 알림] 마이페이지 탈퇴 LoginManager 연동, 알림 functions 추가 및 코드작업

Firebase-Functions/functions/index.js, Firebase-Functions/functions/service/firestoreManager.js, Firebase-Functions/functions/service/withdrawalManager.js, burstcamp/burstcamp/Service/Firebase/FireFunctionsManager.swift
=> [탈퇴] 유저 정보 삭제 함수 생성

burstcamp/burstcamp/Coordinator/TabBar/TabBarCoordinator.swift
- #205
마이페이지 - 로그인화면으로 이동하는 로직 추가했습니다
=> [코디네이터] 마이페이지 - 로그인화면으로 이동

burstcamp/burstcamp/Scene/Tab/MyPage/View/MyPageView.swift, burstcamp/burstcamp/Scene/Tab/MyPage/ViewController/MyPageViewController.swift, burstcamp/burstcamp/Scene/Tab/MyPage/ViewModel/MyPageViewModel.swift, burstcamp/burstcamp/Service/Firebase/FireFunctionsManager.swift, burstcamp/burstcamp/Service/LogInManager.swift, burstcamp/burstcamp/Service/UserManager.swift
- #27 
- #207
1. LoginManager에서 Athentication 삭제
2. 마이페이지에서 Local 정보 삭제 
3. Firebase Functions로 DB 정보 삭제 (Indicator)
4. 모두 삭제후 로그인 화면으로 이동
=> [탈퇴] LoginManager와 마이페이지 연동

burstcamp/burstcamp.xcodeproj/project.pbxproj, burstcamp/burstcamp/App/SceneDelegate.swift, burstcamp/burstcamp/Coordinator/Auth/AuthCoordinator.swift, burstcamp/burstcamp/Coordinator/Base/CoordinatorEvent.swift, burstcamp/burstcamp/Coordinator/Base/GithubLogInCoordinator.swift, burstcamp/burstcamp/Coordinator/MyPage/MyPageCoordinator.swift, burstcamp/burstcamp/Scene/Auth/LogIn/LoginViewController.swift, burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewController.swift, burstcamp/burstcamp/Scene/Auth/SignUp/CamperID/SignUpCamperIDViewController.swift, burstcamp/burstcamp/Scene/Auth/SignUp/Domain/SignUpDomainViewController.swift, burstcamp/burstcamp/Scene/Tab/MyPage/ViewController/MyPageViewController.swift, burstcamp/burstcamp/Scene/Tab/MyPage/ViewModel/MyPageViewModel.swift, burstcamp/burstcamp/Service/KeyChainManager.swift, burstcamp/burstcamp/Service/LogInManager.swift
reAuth 방식을 keychain에 저장된 token이용하는 방식에서 github 로그인으로 변경
=> [회원탈퇴] reAuth 문제 수정

burstcamp/burstcamp/Scene/Auth/LogIn/LogInView.swift, burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogView.swift, burstcamp/burstcamp/Scene/Tab/MyPage/ViewController/MyPageViewController.swift, burstcamp/burstcamp/Scene/Tab/MyPage/ViewModel/MyPageViewModel.swift
- close #227 
- indicator 나타나는 시점 깃허브 로그인 후로 수정
- indicator가 돌아가는 중 (탈퇴중) 화면 터치 불가능
=> [탈퇴] indicator 및 화면 인터렉션 수정

Firebase-Functions/functions/index.js, Firebase-Functions/functions/service/firestoreManager.js
- feed 삭제 시 하위 컬렉션 함께 삭제
- 추천 피드 삭제 후 삽입으로 변경
=> [Functions] feed 삭제 오류 및 추천 피드 수정

burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewController.swift, burstcamp/burstcamp/Service/Firebase/FireFunction/FireFunctionsManager.swift
- json Key 값이 잘못되어있는 오류였습니다.
- blogTitle -> blogURL
=> [회원가입] 블로그 타이틀 불러올때 오류 수정

burstcamp/burstcamp.xcodeproj/project.pbxproj, burstcamp/burstcamp/App/Info.plist
=> [앱 설정] 세로모드 고정

burstcamp/burstcamp/Scene/Auth/LogIn/LoginViewController.swift, burstcamp/burstcamp/Service/Firebase/FireFunction/FireFunctionsManager.swift
=> [로그인] 로그인 제어 불능상태 해결

Firebase-Functions/functions/service/firestoreManager.js
- #253 
- scrapCount 0으로 설정
- thumbnailURL 이 thumbnail로 되어있던데 잘 사용하고 계신 것 같아서 피그마를 고치던지 FeedDB를 고치면 될 것 같습니다.
- feed 저장하는 것만 바꿔서 다른 기능이 잘 안될 것 같아요?
=> Rss Feed 업데이트시 Feed 모델 수정

Firebase-Functions/functions/service/firestoreManager.js, burstcamp/burstcamp/Data/Network/FeedRemoteDataSource.swift, burstcamp/burstcamp/Domain/Model/Feed/Feed.swift, burstcamp/burstcamp/Domain/Model/Feed/FeedAPIModel.swift
- Swift의 FeedAPIModel 수정했습니다.
- writerBlogTitle이 없어서 추가했습니다. Functions, Figma 업데이트 완료
=> [Refactor] 254 refactor db모델 수정 반영 swift에서 사용하는 함수 수정

burstcamp/burstcamp.xcodeproj/project.pbxproj
- close #264 
- 앱 버전 target 14.0 -> 15.0
- 14.0을 지원하기 위해 쏟아야 하는 노력 > 시간 & 개발적으로 배우는 것
- 14.0에 대한 예외처리 및 14.0 ~ 16.0 디버깅도 너무 오래걸림
- 앱 출시를 위해 우선순위가 아니라고 판단되어 변경합니다.
=> [refactor] 앱 버전 target 14.0 -> 15.0

burstcamp/burstcamp/App/SceneDelegate.swift, burstcamp/burstcamp/Data/Repositories/UserRepository/DefaultUserRepository.swift, burstcamp/burstcamp/Domain/Interfaces/UserRepository/UserRepository.swift, burstcamp/burstcamp/Domain/UseCase/Tab/MyPage/DefaultMyPageUseCase.swift, burstcamp/burstcamp/Domain/UseCase/Tab/MyPage/MyPageUseCase.swift, burstcamp/burstcamp/Presentation/Factory/DependencyFactory.swift, burstcamp/burstcamp/Presentation/Tab/MyPage/MyPage/ViewModel/MyPageViewModel.swift, burstcamp/burstcamp/Service/Firebase/Firestore/BCFirestoreService.swift, burstcamp/burstcamp/Service/Singleton/DarkmodeManager.swift, burstcamp/burstcamp/Service/Singleton/KeyChainManager.swift
- close #277 
- myPageViewModel  로직 -> UseCase
- Service/Singleton 클래스는 다 UseCase에서 호출하려고 함
- 이슈에 달려있는 Label을 PR에 자동 연계하는 방법 없을까..
=> [Refactor] 마이 페이지 usecase 생성

burstcamp/burstcamp/Domain/Model/Feed/Feed.swift, burstcamp/burstcamp/Domain/Model/Feed/FeedWriter.swift, burstcamp/burstcamp/Presentation/Tab/Home/ViewController/HomeViewController.swift, burstcamp/burstcamp/Presentation/Tab/Home/ViewModel/HomeViewModel.swift
- 더 쉽고 강력한 CollectionView를 위해 diffable datasource로 변경
- HomeViewController에서만 변경
- DiffableDataSource는 다른 섹션에 다른 Model을 넣어줘야함. 현재 추천 섹션과 일반 섹션에 같은 Feed를 사용하고 있어 추천 섹션은 Load 가 안됨. 다음 PR에서 모델 수정 필요.
- 모아보기에도 Diffable 적용 필요
- 다른 섹션 <-> 다른 모델 참고 링크 : https://applecider2020.tistory.com/38
=> [Refactor]collectionview -> diffable datasource로 변경

burstcamp/burstcamp/Presentation/Coordinator/Base/CoordinatorEvent.swift, burstcamp/burstcamp/Presentation/Coordinator/Home/HomeCoordinator.swift, burstcamp/burstcamp/Presentation/Tab/Home/ViewController/HomeViewController.swift
- close #289 
- 추천피드 클릭시 사파리로 이동
=> feat: Coordinator에게 URL 전달해서 Safari 연동

Firebase-Functions/functions/service/feedAPI.js
- catch 문 위치 변경
- codeTag가 없는 경우 for문을 돌지 않음
=> [Fix] Cloud Functions에서 피드업데이트 에러

burstcamp/burstcamp/Presentation/Auth/SignUp/Blog/SignUpBlogViewController.swift, burstcamp/burstcamp/Presentation/Auth/SignUp/Blog/SignUpBlogViewModel.swift, burstcamp/burstcamp/Presentation/Coordinator/MyPage/MyPageCoordinator.swift, burstcamp/burstcamp/Presentation/Tab/Detail/ViewController/FeedDetailViewController.swift, burstcamp/burstcamp/Presentation/Tab/Detail/ViewModel/FeedDetailViewModel.swift, burstcamp/burstcamp/Presentation/Tab/Home/View/HomeView.swift, burstcamp/burstcamp/Presentation/Tab/Home/ViewController/HomeViewController.swift, burstcamp/burstcamp/Presentation/Tab/Home/ViewModel/HomeViewModel.swift, burstcamp/burstcamp/Presentation/Tab/MyPage/MyPage/ViewController/MyPageViewController.swift, burstcamp/burstcamp/Presentation/Tab/MyPage/MyPage/ViewModel/MyPageViewModel.swift, burstcamp/burstcamp/Presentation/Tab/ScrapPage/ViewController/ScrapPageViewController.swift, burstcamp/burstcamp/Presentation/Tab/ScrapPage/ViewModel/ScrapPageViewModel.swift, burstcamp/burstcamp/Service/Singleton/UserManager.swift, burstcamp/burstcamp/Util/Error/ViewModel/HomeViewModelError.swift, burstcamp/burstcamp/Util/Extension/UI/ViewController/UIViewController+.swift
- close #323 
- 기존에 ViewController & ViewModel에서 얽히고 얽혀있던 Combine을 정리했습니다.
- ViewModel에서 cancelBag을 모두 없앴습니다.
- Toast Message 가 안뜨던 에러 수정
- Dispatch Queue 위치 조정 
- 회원가입부터 탈퇴, 스크랩 까지 대부분 QA를 했지만 안되는게 있을 수도 있습니다. 확인하면 제보 부탁드립니다.
- https://velog.io/@dawn_dancer/iOS-Rx-MVVM%EC%9D%98-%EC%98%AC%EB%B0%94%EB%A5%B8-%EC%82%AC%EC%9A%A9%EB%B2%95-saebyuckchoom
=> [Refactor] MVVM Input <-> Output

burstcamp/burstcamp/Presentation/Tab/Home/ViewController/HomeViewController.swift, burstcamp/burstcamp/Presentation/Tab/Home/ViewModel/HomeViewModel.swift, burstcamp/burstcamp/Presentation/Tab/ScrapPage/ViewController/ScrapPageViewController.swift, burstcamp/burstcamp/Presentation/Tab/ScrapPage/ViewModel/ScrapPageViewModel.swift
- close #342 
- cancel Bag 변경
- 기존에 cell cancelBag에 저장하던걸, Input - output 패턴 수정하면서 ViewController cancel Bag에 저장했음. -> 다시 cell.cancelBag에 버튼 publisher 구독 저장
=> [Fix] 다중 스크랩 에러 해결

burstcamp/burstcamp.xcodeproj/project.pbxproj, burstcamp/burstcamp/Presentation/Tab/Home/ViewController/HomeViewController.swift, burstcamp/burstcamp/Presentation/Tab/ScrapPage/ViewController/ScrapPageViewController.swift, burstcamp/burstcamp/Util/Protocol/ContainScrollViewController.swift
- close #346 
- 현재 있는 위치해있는 탭 바를 클릭하면 최상단으로 이동합니다.
- HomeViewController에서 tabBarController Delegate를 채택해 구현했습니다. 
- ContainScrollviewViewController를 채택한 Home과 ScrapPage에서만 가능합니다.
- 모아보기에서도 네비게이션바를 누르면 스크롤 최상단으로 이동합니다. (기존에 홈에서만 가능)
https://user-images.githubusercontent.com/71776532/216779832-fd91dda3-701f-4e6b-bb62-0e0e0567ee33.mov
=> [Feat] 탭 바 클릭시 스크롤 최상단 이동
