boostcampwm-2022/iOS09-burstcamp

- Eoljuga/Eoljuga/Resource/Assets.xcassets/Colors/Contents.json
- Eoljuga/Eoljuga/Resource/Assets.xcassets/Colors/black.colorset/Contents.json
- Eoljuga/Eoljuga/Resource/Assets.xcassets/Colors/blue.colorset/Contents.json
- Eoljuga/Eoljuga/Resource/Assets.xcassets/Colors/green.colorset/Contents.json
- Eoljuga/Eoljuga/Resource/Assets.xcassets/Colors/indigo.colorset/Contents.json
- Eoljuga/Eoljuga/Resource/Assets.xcassets/Colors/orange.colorset/Contents.json
- Eoljuga/Eoljuga/Resource/Assets.xcassets/Colors/pink.colorset/Contents.json
- Eoljuga/Eoljuga/Resource/Assets.xcassets/Colors/purple.colorset/Contents.json
- Eoljuga/Eoljuga/Resource/Assets.xcassets/Colors/red.colorset/Contents.json
- Eoljuga/Eoljuga/Resource/Assets.xcassets/Colors/teal.colorset/Contents.json
- Eoljuga/Eoljuga/Resource/Assets.xcassets/Colors/white.colorset/Contents.json
- Eoljuga/Eoljuga/Resource/Assets.xcassets/Colors/yellow.colorset/Contents.json
- #4 
- Custom Color Set 추가
- 다크모드에서도 색이 바뀌지 않는 `white` `black` 컬러도 함께 추가했습니다.
- 없음
- FigmaExport 실패 후 노가다 작업
> [Color] Custom Color Set 추가

- Eoljuga/Eoljuga.xcodeproj/project.pbxproj
- Eoljuga/Eoljuga/Scene/Tab/MyPage/View/OpenSourceLicenseView.swift
- Eoljuga/Eoljuga/Scene/Tab/MyPage/ViewController/OpenSourceLicenseViewController.swift
- close #72 
- (오픈소스이름, 링크 주소) 마다 label과 button 스택뷰를 만들어 View에 추가해주었습니다.
- 오픈소스가 세개뿐이라 굳이 테이블뷰로 만들지 않았습니다.
- 사파리로 링크 타고 들어가는 부분은 마이페이지 코디네이터 작업에서 할 예정입니다.
> [마이페이지] 오픈소스 라이선스 View 구현

- burstcamp/burstcamp/Coordinator/AuthCoordinator.swift
- burstcamp/burstcamp/Coordinator/AuthCoordinatorEvent.swift
- burstcamp/burstcamp/Scene/Auth/LogIn/LoginViewController.swift
- burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewController.swift
- burstcamp/burstcamp/Scene/Auth/SignUp/SignUpViewModel.swift
- burstcamp/burstcamp/Service/LogInManager.swift
- close #7 
- 기관 인증 후 FirebaseStore의 fetchUser 함수로 회원가입 여부 판단
- 회원가입 필요하면 userUUID와 nickname을 파라미터로 넣고 Domain선택 창으로 이동
- 회원가입이 되어있으면 TabBar로 이동
- Need: 에러처리를 더 명확히 할 필요가 있음
> feat: 자동로그인 구현, 멤버 여부에 따른 로직, 가입 되어있는지에 따른 로직 추가

- Firebase-Functions/functions/model.js
- Firebase-Functions/functions/package-lock.json
- Firebase-Functions/functions/package.json
- Firebase-Functions/functions/service/feedAPI.js
- Firebase-Functions/functions/service/firestoreManager.js
- Firebase-Functions/functions/util.js
- burstcamp/burstcamp/Model/Feed/Feed.swift
- burstcamp/burstcamp/Model/Feed/FeedDTO.swift
- burstcamp/burstcamp/Scene/Common/View/NormalFeedCell/Main/NormalFeedCellMain.swift
- burstcamp/burstcamp/Scene/Tab/Detail/View/FeedDetailView.swift
- burstcamp/burstcamp/Scene/Tab/Detail/ViewModel/FeedDetailViewModel.swift
- burstcamp/burstcamp/Scene/Tab/Home/ViewController/HomeViewController.swift
파베 작업 했습니다.
이제 feed를 파싱할 때, writerUUID도 함께 저장합니다.
이제 파싱된 정보를 클라이언트에서 그대로 사용해도 오류가 안납니다.
암호화엔 취약하지만 범용적인 hash함수인 `MD5`를 사용했습니다.
> 데이터베이스끼리의 연동을 위한 데이터수집 로직 개선

- burstcamp/burstcamp.xcodeproj/project.pbxproj
- burstcamp/burstcamp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- burstcamp/burstcamp/Scene/Tab/Home/ViewModel/HomeViewModel.swift
- burstcamp/burstcamp/Scene/Tab/MyPage/ViewController/MyPageViewController.swift
- burstcamp/burstcamp/Scene/Tab/ScrapPage/ViewController/ScrapPageViewController.swift
- burstcamp/burstcamp/Scene/Tab/ScrapPage/ViewModel/ScrapPageViewModel.swift
- burstcamp/burstcamp/Service/LogInManager.swift
- burstcamp/burstcamp/Util/Extension/UI/UICollectionView+emptyView.swift
- close #75 
- close #142 
- 사용자가 가지고있는 scrapFeedUUIDs를 기반으로 Feed를 비동기호출합니다. 현재 user에서 에러가 발생해 목업 데이터로 대체했습니다.
- 구독한 피드가 없을 때 보여주는 empty View를 구현했습니다.
- 로직은 아래 그림 참고부탁드립니다.
https://user-images.githubusercontent.com/71776532/205419373-eb8ae2df-a449-4ab7-b9e2-2beaac8661fa.mp4
- 함수 이름을 fetch로 통일했습니다. 클린코드를 위해서 request, fetch 등의 용어를 통일할 필요가 있어보입니다.
- 플래그 변수(isFetching, canFetchMoreData)를 깔끔하게 다루기 위한 방법을 고민하고 있습니다. Combine을 사용해 네트워크 처리 전 후로 설정을 해주려는데 좋은 의견있으면 부탁드리겠습니다.
- 한 화면에 피드가 5개씩 들어가는데 80% 이상일 때 페이지네이션 요청이되는 지 확인하기 위해 한 번에 요청하는 개수를 7개로 설정했습니다. 추후에 홈과 10개로 통일할 예정입니다.
> [모아보기] 유저 ScrapFeedUUIDs 기반으로 파이어베이스 호출

- burstcamp/burstcamp/Scene/Common/View/NormalFeedCell/NormalFeedCell.swift
- burstcamp/burstcamp/Scene/Common/ViewModel/FeedScrapViewModel.swift
- burstcamp/burstcamp/Scene/Tab/Home/View/FeedCellType.swift
- burstcamp/burstcamp/Scene/Tab/Home/ViewController/HomeViewController.swift
- burstcamp/burstcamp/Scene/Tab/Home/ViewModel/HomeViewModel.swift
- burstcamp/burstcamp/Scene/Tab/ScrapPage/ViewController/ScrapPageViewController.swift
- burstcamp/burstcamp/Scene/Tab/ScrapPage/ViewModel/ScrapPageViewModel.swift
- close #178 
- 스크랩 버튼을 누르면 count up & down이 표시됩니다.
- 정책에 따라 로컬 변경 값만 반영합니다. 실시간 업데이트 값을 보려면 refresh해줘야 합니다.   
- 현재 로직 (피그마에 있음)
- 현재 feed데이터를 HomeViewModel이 가지고 있어서 위 그림과 같은 구조가 되었습니다. Cell의 스크랩 버튼을 누르면 CellViewModel에서 네트워크처리를 하고 HomeViewModel에서 모델을 수정해줘야 합니다. CellViewModel과 관련해 더 괜찮은 구조가 있다면 가감없이 코멘트 부탁드립니다.  
- 마지막 MVP!
> [스크랩] 스크랩 클릭시 로컬에서 Up & Down 처리

- burstcamp/burstcamp/Service/ImageCacheManager.swift
- burstcamp/burstcamp/Util/Constant/Constant.swift
- burstcamp/burstcamp/Util/Extension/UI/UIImageView+Cache.swift
- close #186 
https://luen.tistory.com/210
NSCache 정책은 100개 사진, 100MB 인데 삭제가 너무 빈번히 일어나서 다시 확인해봐야합니다.
print문 또 쓸거에요!
이슈 참조
> [이미지 캐시] 정책 개선 및 사이즈 개선

- burstcamp/burstcamp.xcodeproj/project.pbxproj
- burstcamp/burstcamp/App/SceneDelegate.swift
- burstcamp/burstcamp/Coordinator/App/AppCoordinator.swift
- burstcamp/burstcamp/Coordinator/Auth/AuthCoordinator.swift
- burstcamp/burstcamp/Coordinator/Base/CoordinatorEvent.swift
- burstcamp/burstcamp/Scene/Auth/LogIn/LogInView.swift
- burstcamp/burstcamp/Scene/Auth/LogIn/LoginViewController.swift
- burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogView.swift
- burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewController.swift
- burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewModel.swift
- burstcamp/burstcamp/Scene/Auth/SignUp/CamperID/SignUpCamperIDView.swift
- burstcamp/burstcamp/Scene/Auth/SignUp/Domain/SighUpDomainView.swift
- burstcamp/burstcamp/Service/KeyChainManager.swift
- burstcamp/burstcamp/Service/LogInManager.swift
- burstcamp/burstcamp/Util/Constant/Constant.swift
- burstcamp/burstcamp/Util/Error/FirebaseAuthError.swift
- burstcamp/burstcamp/Util/Error/FirestoreError.swift
- modules/BCResource/BCResource/Generated/Assets+Generated.swift
- close #200 
- close #206 
- close #199 
- 변경전
- 변경후
- 리뷰어님께서 말씀하신 뷰 추가와 레이아웃 처리하는 부분 분리
- indicator아래에 상태설명 라벨 추가
- 회원가입시 토큰 저장
- 탈퇴시 토큰을 이용한 재인증 후 탈퇴처리
- 캠퍼 인증 버튼에 github 로고 추가
- addViews, configureLayout으로 해놨는데 더 좋은 이름 추천받습니다
- 디자이너님께서는 indicator아래 label의 글자 색과 크기 등을 알려주시면 수정하겠습니다
> [회원가입] indicator 하단뷰, 탈퇴시 재인증처리

- burstcamp/burstcamp/App/AppDelegate.swift
- burstcamp/burstcamp/App/Info.plist
- burstcamp/burstcamp/Coordinator/App/AppCoordinator.swift
- burstcamp/burstcamp/Coordinator/Home/HomeCoordinator.swift
- burstcamp/burstcamp/Coordinator/TabBar/TabBarCoordinator.swift
- burstcamp/burstcamp/Scene/Tab/Home/ViewController/HomeViewController.swift
- burstcamp/burstcamp/Service/Firebase/FirestoreCollection.swift
- burstcamp/burstcamp/Service/FirestoreFCMToken.swift
- burstcamp/burstcamp/Service/UserDefaultsManager.swift
- modules/BCResource/BCResource/Generated/Assets+Generated.swift
- #211 
- foreground
- UserDefaults - isForeground && feedUUID
- NotificationCenter .Push로 보내서 TabCoordinator에서 받습니다.
- TabCoordinator에서 어디화면에 있든 디테일 뷰를 띄워줍니다.
- background
- UserDefaults - feedUUID
- HomeCoordinator가 start됐을때 isForeground false && feedUUID를 가지고 디테일 뷰를 띄워줍니다.
> [푸시알림] 탭했을시 Coordinator 이동

- burstcamp/burstcamp/App/AppDelegate.swift
- burstcamp/burstcamp/Service/UserDefaultsManager.swift
- burstcamp/burstcamp/Util/Extension/UI/UIImageView+Cache.swift
etag 정보들이 UserDefaults에 남아있어 메모리 캐시 특성상 앱 종료시 삭제되니 같이 삭제해주었습니다.
> [캐시] etag 정보 삭제

- Firebase-Functions/functions/service/apnsManager.js
- Firebase-Functions/functions/service/firestoreManager.js
- burstcamp/burstcamp/Coordinator/Home/HomeCoordinator.swift
- burstcamp/burstcamp/Coordinator/TabBar/TabBarCoordinator.swift
- #211 
- 알림 백그라운드에서 탭할때 디테일뷰로 이동하지 않는 버그
- HomeCoordinator가 준비되기전에 Push해서 발생한 버그라고 생각해서 TabBarCoordinator가 모두 준비되면 디테일뷰로 이동하도록 처리했습니다.
- 기존 HomeCoordinator 처리 -> TabBarCoordinator 처리
- 유효하지 않는 fcmToken 토큰 있을때 제외하고 알림 전송
> [알림] 디테일뷰로 가지 않는 버그 수정

- Firebase-Functions/functions/index.js
- Firebase-Functions/functions/service/firestoreManager.js
- burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewModel.swift
- burstcamp/burstcamp/Scene/Common/View/DefaultBadgeView.swift
- burstcamp/burstcamp/Util/Constant/URLRegularExpression.swift
- #241 
- 회원가입시 추가한 블로그 주소를 포함하여 Feed DB 업데이트하기 위한 FeedDB 업데이트 함수 `updateFeedDBWhenSignup` Functions 생성
- 회원가입시 블로그 입력받을 때 마지막 "/" 포함 가능하도록 변경
- "/" 포함시 DB에는 삭제 후 저장
> [버그수정] 블로그 주소 마지막 "/" 처리 및 Feed 업데이트 함수 생성

- burstcamp/burstcamp/App/AppDelegate.swift
- burstcamp/burstcamp/Coordinator/TabBar/TabBarCoordinator.swift
- burstcamp/burstcamp/Service/UserDefaultsManager.swift
- #211 
알림 클릭시 => UserDefaults에 feedUUID 저장
- Suspended 알림받기 + Suspended 실행 => (app 코디네이터 start 후) UserDefaults feedUUID 확인, UserDefaults 삭제
- Suspended 알림받기 + foreground 실행 => (app 코디네이터 start 후) UserDefaults feedUUID 확인, UserDefaults 삭제
- background 알림받기 + background 실행 => (app 코디네이터 살아있음) NotificationCenter, UserDefaults 삭제
- background 알림받기 + foreground 실행 => (app 코디네이터 살아있음) NotificationCenter, UserDefaults 삭제
> [푸시알림] 백그라운드 이동 버그 수정

- burstcamp/burstcamp/Scene/Tab/MyPage/View/MyPageEditView.swift
- burstcamp/burstcamp/Service/ImageCacheManager.swift
- burstcamp/burstcamp/Util/Extension/UI/UIImageView+Cache.swift
- #31 
이미지의 etag를 확인하는 과정에서 네트워크 요청을 기다리기 전에 로컬 캐시가 있다면 우선 반환하도록 코드를 수정했습니다.
고쳐야 할 것은 cancelBag이 ImageCacheManager것을 가져다 써서 cancel이 일어나지 않는다는 에러사항이 있습니다..
> [캐시] 네트워크 요청 전 로컬 캐시 이미지 반환

- burstcamp/burstcamp.xcodeproj/project.pbxproj
- burstcamp/burstcamp/Domain/UseCase/Tab/Detail/DefaultFeedDetailUseCase.swift
- burstcamp/burstcamp/Domain/UseCase/Tab/Detail/FeedDetailUseCase.swift
- burstcamp/burstcamp/Presentation/Coordinator/Base/ContainFeedDetailCoordinator.swift
- burstcamp/burstcamp/Presentation/Coordinator/Home/HomeCoordinator.swift
- burstcamp/burstcamp/Presentation/Factory/DependencyFactory.swift
- burstcamp/burstcamp/Presentation/Tab/Detail/ViewController/FeedDetailViewController.swift
- burstcamp/burstcamp/Presentation/Tab/Detail/ViewModel/FeedDetailViewModel.swift
- burstcamp/burstcamp/Presentation/Tab/Home/ViewController/HomeViewController.swift
- burstcamp/burstcamp/Util/Error/ViewModel/FeedDetailViewModelError.swift
- burstcamp/burstcamp/Util/Protocol/ContainFeedDetailViewController.swift
- close #284 
- FeedDetail에서 스크랩
- ScrapViewModel 제거
- 스크랩 완료시 ContainFeedDetailViewController 프로토콜을 채택한 ViewController에게 업데이트 된 피드를 전달함. 현재는 HomeViewController만 채택하고 있어, Home -> FeedDetail 플로우에서 스크랩/스크랩 해제시 HomeView도 업데이트 함
- FeedDetail 들어갈 때 스크랩 여부 체크
https://user-images.githubusercontent.com/71776532/213866884-acee4536-2316-440e-9950-31e94ce07da3.mp4
https://user-images.githubusercontent.com/71776532/213866887-84cc0fe2-eedd-47c4-a8a0-daf574718b72.mp4
> Feature/284 feat feeddetail에서 스크랩 시 home에도 적용

- burstcamp/burstcamp.xcodeproj/project.pbxproj
- burstcamp/burstcamp/Data/Repositories/FeedRepository/DefaultFeedRepository.swift
- burstcamp/burstcamp/Domain/Interfaces/FeedRepository/FeedRepository.swift
- burstcamp/burstcamp/Domain/UseCase/Tab/Home/DefaultHomeUseCase.swift
- burstcamp/burstcamp/Domain/UseCase/Tab/ScrapPage/DefaultScrapPageUseCase.swift
- burstcamp/burstcamp/Domain/UseCase/Tab/ScrapPage/ScrapPageUseCase.swift
- burstcamp/burstcamp/Presentation/Common/View/NormalFeedCell/NormalFeedCell.swift
- burstcamp/burstcamp/Presentation/Coordinator/ScrapPage/ScrapPageCoordinator.swift
- burstcamp/burstcamp/Presentation/Factory/DependencyFactory.swift
- burstcamp/burstcamp/Presentation/Tab/Detail/ViewModel/FeedDetailViewModel.swift
- burstcamp/burstcamp/Presentation/Tab/Home/View/RecommendFeedSection/RecommendFeedCell.swift
- burstcamp/burstcamp/Presentation/Tab/Home/ViewController/HomeViewController.swift
- burstcamp/burstcamp/Presentation/Tab/Home/ViewModel/HomeViewModel.swift
- burstcamp/burstcamp/Presentation/Tab/ScrapPage/View/ScrapPageView.swift
- burstcamp/burstcamp/Presentation/Tab/ScrapPage/ViewController/ScrapPageViewController.swift
- burstcamp/burstcamp/Presentation/Tab/ScrapPage/ViewModel/ScrapPageViewModel.swift
- burstcamp/burstcamp/Service/Firebase/Firestore/BCFirestoreService.swift
- burstcamp/burstcamp/Service/Firebase/Firestore/FirestoreServiceError.swift
- burstcamp/burstcamp/Service/Singleton/UserManager.swift
- burstcamp/burstcamp/Util/Error/ViewModel/ScrapViewModelError.swift
- close #286 
- scrapPage Use Case 구현 
- 최근 스크랩 피드 불러오기
- 페이지네이션으로 추가 스크랩 피드 불러오기
- 스크랩/언스크랩
- Diffable 적용
- 스크랩 카운트 - 1 안되던 오류 해결
- UserListner에서 UserManager - user 업데이트 안 하던 거 수정
- Empty View 적용
- Home, ScrapPage, FeedDetail 모두 연계 잘됨
- Home - FeedDetail 스크랩 연계 됨
-  ScrapPage - FeedDetail 스크랩 연계 됨
- But, Home 탭에서 스크랩 한 거를 ScrapPage 탭 에서 확인하려면 refresh 해줘야하고, 
Scrap Page 탭에서 스크랩/언스크랩한 거를 확인하려면 Home 탭에서 Refresh해줘야 함.
각 탭은 다른 화면이라고 생각하면 될 듯. 
지금은 홈에 피드가 적지만, 피드가 많아지면 스크랩 -> 홈으로가서 확인하는 일이 적음. 굳이 UnScrap 할 때마다 HomeView를 reload 해줄 필요 없음. 유저가 Refresh하는 플로우는 자연스럽다고 판단 됨
- Diffable을 처음 사용해보는데 잘 쓰고 있는 건지 헷갈림. 레퍼런스 보고 공부가 더 필요.
- 스크랩한 피드가 없을 때 에러처리를 통해 관리하고 있음. 더 깔끔하게 관리할 방법 있으면 좋겠음.
- 다음에 Recommend Cell 만 처리해주면 기본 기능은 사실상 전부 수정 완료.
> [Feature]scrappage usecase 구현

- burstcamp/burstcamp.xcodeproj/project.pbxproj
- burstcamp/burstcamp/Data/Local/FeedSingletonDataSource.swift
- burstcamp/burstcamp/Data/Network/FeedRemote/FeedRemoteDataSource.swift
- burstcamp/burstcamp/Domain/Model/Feed/DiffableFeed.swift
- burstcamp/burstcamp/Domain/Model/Feed/Feed.swift
- burstcamp/burstcamp/Domain/UseCase/Tab/Home/DefaultHomeUseCase.swift
- burstcamp/burstcamp/Presentation/Tab/Home/ViewController/HomeViewController.swift
- close #281 
- DiffableFeed 생성
- Diffable DataSource의 경우  여러 개의 섹션에 동일한 Item이 들어갈 수 없음.
- Feed를 래핑하는 DiffableFeed enum 타입을 만듦
- ViewController에서 FeedList를 받아 래핑해서 Snapshot에 넣어줌
- Carousel(가로 무한 스크롤)을 위한 목업데이터 생성
- Diffable Datasource의 경우 스냅샷에 똑같은 아이템이 안 들어감
- 기존 Carousel View의 경우 아이템 좌, 우로 똑같은 를 만들어줬음. ex) 추천피드가 3개인 경우 3 + 3 + 3으로 피드를 구성했음
- Diffbable의 경우 Hashable 해야함. Feed UUID를 새로 생성해서 목업 데이터를 만들어줌
- 3(FeedUUID가 다른 목업 피드) + 3(추천 피드) + 3(FeedUUID가 다른 목업 피드)
- Diffable + Carousel View를 위한 더 좋은 방법이 있다면 알고 싶다.
https://hsnxcr.medium.com/uicollectionviewdiffabledatasource-wrapper-for-handling-multiple-section-layout-and-more-1c387b01d179
> [Refactor] Diffable DataSource 를 위한 DiffableFeed

- burstcamp/burstcamp/Util/Extension/UI/View/UILabel+LineHeight.swift
- close #293 
- UILabel에 BaseLine Offset 적용
- Text 세로 가운데 정렬 함
|적용 전|적용 후 1|적용 후 2 |
|:---:|:---:|:---:|
|<img width = 200 src = "https://user-images.githubusercontent.com/71776532/214769266-300c2010-4ab0-41db-8f26-165da2468aa7.png">|<img width = 200 src = "https://user-images.githubusercontent.com/71776532/214769270-c6ac3208-0530-4649-9f74-92b0d1b4c5ff.png">|<img width = 200 src = "https://user-images.githubusercontent.com/71776532/214769276-0c19962f-5dde-4261-be88-8a04556f7860.png">|
"적용 후 2" 에서 덧칠 된 부분이 1 줄임. 세로 가운데 정렬된 거를 확인할 수 있음
- https://sujinnaljin.medium.com/swift-label%EC%9D%98-line-height-%EC%84%A4%EC%A0%95-%EB%B0%8F-%EA%B0%80%EC%9A%B4%EB%8D%B0-%EC%A0%95%EB%A0%AC-962f7c6e7512
- http://blog.eppz.eu/uilabel-line-height-letter-spacing-and-more-uilabel-typography-extensions/
> [Feat] UILabel에 baseLineOffset 적용

- burstcamp/burstcamp.xcodeproj/project.pbxproj
- burstcamp/burstcamp/Data/Repositories/UserRepository/DefaultUserRepository.swift
- burstcamp/burstcamp/Domain/Interfaces/UserRepository/UserRepository.swift
- burstcamp/burstcamp/Domain/UseCase/Auth/Login/DefaultLoginUseCase.swift
- burstcamp/burstcamp/Domain/UseCase/Auth/Login/LoginUseCase.swift
- burstcamp/burstcamp/Domain/UseCase/Tab/MyPage/DefaultMyPageUseCase.swift
- burstcamp/burstcamp/Presentation/Auth/LogIn/ViewModel/LogInViewModel.swift
- burstcamp/burstcamp/Presentation/Factory/DependencyFactory.swift
- burstcamp/burstcamp/Service/Singleton/UserManager.swift
- burstcamp/burstcamp/Util/Error/Repository/UserRepositoryError.swift
- burstcamp/burstcamp/Util/Error/UseCase/LoginUseCaseError.swift
- close #295 
- 로그인 시 firestore에 User 정보 있는지 확인
- 있으면 TabBar로
- 없으면 Auth로
- 기존 기기에서 이전 버전이 깔려있으면 로그인은 되어있는데 KeyChain에 값이 없는 경우가 있어서 에러가 발생했음. 이를 막기 위해 KeyChain 값이 nil이면 로그아웃으로 판별함
- 재로그인시 KeyChain에 값이 저장
- 현재 로그인하고 HomeViewController로 넘어가면 에러가 발생함. didFailToRegisterForRemoteNotificationsWithError
- UNUserNotificationCenterDelegate를 주석 처리해놔서 그런거 같음. 이거 때문에 로그인해서 Home화면 들어가면 화면이 안 움직임. 추후 주석 풀고 제대로 동작하는지 확인해봐야겠음.
> [Fix] 295 에러 다른 기기에서 로그인시 재 가입해야하던 오류

- burstcamp/burstcamp/Domain/UseCase/Tab/Home/DefaultHomeUseCase.swift
- burstcamp/burstcamp/Domain/UseCase/Tab/Home/HomeUseCase.swift
- burstcamp/burstcamp/Presentation/Factory/DependencyFactory.swift
- burstcamp/burstcamp/Presentation/Tab/Home/ViewController/HomeViewController.swift
- burstcamp/burstcamp/Presentation/Tab/Home/ViewModel/HomeViewModel.swift
- burstcamp/burstcamp/Service/Singleton/UserManager.swift
- burstcamp/burstcamp/Util/Error/ViewModel/HomeViewModelError.swift
UseCase로 이동
- close #297 
- HomviewController에서 push 상태 저장 로직 -> UseCase로 이동
> [Refactor] HomeViewController에서 FirestoreService 제거

- burstcamp/burstcamp.xcodeproj/project.pbxproj
- burstcamp/burstcamp/App/SceneDelegate.swift
- burstcamp/burstcamp/Data/Repositories/LoginRepository/DefaultLoginRepository.swift
- burstcamp/burstcamp/Data/Repositories/UserRepository/DefaultUserRepository.swift
- burstcamp/burstcamp/Domain/Interfaces/LoginRepository/LoginRepository.swift
- burstcamp/burstcamp/Domain/Interfaces/UserRepository/UserRepository.swift
- burstcamp/burstcamp/Domain/Model/User/Domain.swift
- burstcamp/burstcamp/Domain/Model/User/Login/LoginProvider.swift
- burstcamp/burstcamp/Domain/Model/User/User.swift
- burstcamp/burstcamp/Domain/UseCase/Auth/Login/DefaultLoginUseCase.swift
- burstcamp/burstcamp/Domain/UseCase/Auth/Login/LoginUseCase.swift
- burstcamp/burstcamp/Domain/UseCase/Tab/MyPage/DefaultMyPageUseCase.swift
- burstcamp/burstcamp/Domain/UseCase/Tab/MyPage/MyPageUseCase.swift
- burstcamp/burstcamp/Presentation/Auth/LogIn/View/LogInView.swift
- burstcamp/burstcamp/Presentation/Auth/LogIn/ViewController/LogInViewController.swift
- burstcamp/burstcamp/Presentation/Auth/LogIn/ViewModel/LogInViewModel.swift
- burstcamp/burstcamp/Presentation/Common/Base/AppleAuthViewController.swift
- burstcamp/burstcamp/Presentation/Common/View/Button/AuthButton.swift
- burstcamp/burstcamp/Presentation/Common/View/ImageView/DefaultProfileImageView.swift
- burstcamp/burstcamp/Presentation/Coordinator/App/AppCoordinator.swift
- burstcamp/burstcamp/Presentation/Tab/MyPage/MyPage/View/MyPageProfileView.swift
- burstcamp/burstcamp/Presentation/Tab/MyPage/MyPage/View/MyPageView.swift
- burstcamp/burstcamp/Presentation/Tab/MyPage/MyPage/ViewController/MyPageViewController.swift
- burstcamp/burstcamp/Presentation/Tab/MyPage/MyPage/ViewModel/MyPageViewModel.swift
- burstcamp/burstcamp/Service/Firebase/Auth/BCFirebaseAuthService.swift
- burstcamp/burstcamp/Util/Error/Repository/UserRepository/UserRepositoryError.swift
- burstcamp/burstcamp/Util/Extension/Combine/UIControl+Combine.swift
- burstcamp/burstcamp/Util/Extension/Type/String+sha256.swift
- burstcamp/burstcamp/Util/Extension/UI/ViewController/UIViewController+.swift
- burstcamp/burstcamp/burstcamp.entitlements
- close #307 
- 애플 로그인을 추가했습니다. 로그인 시 게스트 모드로 로그인 됩니다.
- Firebase에서 Apple 로그인 추가 설정
- Apple Developer에서 추가 설정
- XCode에서 설정
- 게스트 추가
- Domain에 Guest를 추가했습니다. 애플 로그인이 완료되면 Guest 정보가 생성되고 바로 탭바로 이동합니다.
- Guest 닉네임은 "Guest-\(userUUID앞 6자리)" 입니다.
- 게스트인 경우 피드 보기, 스크랩, 알림 설정, 다크모드가 가능합니다.
- 내 정보 수정하기가 불가능합니다.
- Guest는 MyPage에서 View가 다르게 설정됩니다.
- AppleAuthViewController 클래스를 구현했습니다.
- Apple Login이 필요한 LoginViewController와 MyPageViewController(탈퇴를 위한 재로그인)에서 상속을 받아 사용합니다.
- Auth Button을 만들었습니다.
- 애플 로그인과 깃헙 로그인을 위한 버튼을 만들었습니다. 애플에서 제공하는 asAuthorizationAppleIDButton도 있지만 Github과의 통일성을 위해 커스텀이 필요했고, SFSymbol의 이미지를 사용해 구현했습니다. 
애플 버튼이 추가된 모습
|라이트 모드| 다크 모드|
|:---:|:---:|
|<img width = 300 src = "https://user-images.githubusercontent.com/71776532/215446119-d3cfb66a-b5f2-4b8c-ae3a-ad7012448983.PNG" …
> [Feature] 애플 로그인으로 게스트 모드 로그인

- burstcamp/burstcamp.xcodeproj/project.pbxproj
- burstcamp/burstcamp/Data/Local/FeedMockUpDatasource.swift
- burstcamp/burstcamp/Data/Repositories/FeedRepository/DefaultFeedRepository.swift
- burstcamp/burstcamp/Data/Repositories/FeedRepository/MockUpFeedRepository.swift
- burstcamp/burstcamp/Domain/Interfaces/FeedRepository/FeedRepository.swift
- burstcamp/burstcamp/Domain/Model/Feed/FeedWriter.swift
- burstcamp/burstcamp/Domain/UseCase/Auth/SignUp/DefaultSignUpUseCase.swift
- burstcamp/burstcamp/Domain/UseCase/Tab/Home/DefaultHomeUseCase.swift
- burstcamp/burstcamp/Presentation/Auth/LogIn/ViewModel/LogInViewModel.swift
- burstcamp/burstcamp/Presentation/Common/View/RecommendCell/RecommendFeedCell.swift
- burstcamp/burstcamp/Presentation/Common/View/RecommendCell/RecommendFeedUserView.swift
- burstcamp/burstcamp/Presentation/Factory/DependencyFactory.swift
- burstcamp/burstcamp/Presentation/Tab/Home/ViewModel/HomeViewModel.swift
- burstcamp/burstcamp/Presentation/Tab/ScrapPage/ViewModel/ScrapPageViewModel.swift
- burstcamp/burstcamp/Util/Error/Repository/FeedRepository/FeedRepositoryError.swift
- close #309 
- 현재 가로 무한 스크롤을 위해서는 추천 피드가 최소 3개이상 필요함. 이를 위해 추천피드가 3개 이하 일 때 공지 피드 생성
- 추천 피드에 url이 없는 경우 userInteraction disable 해줌
- 추천 피드 유저가 프로필이미지가 없는 경우 버캠이로 대체
- 피드 요청 시 피드가 없어 발생하는 에러 -> FeedRepository에서 처리
- 기존에 ViewModel에서 처리
-  FeedRepository에서 에러를 catch해 피드가 없다면 빈 배열을 리턴해주는게 맞다고 생각함
|피드 1 개일 때| 피드 2 개일 때| 피드 3 개일 때|
|:---:|:---:|:---:|
|<img width = 250 src = "https://user-images.githubusercontent.com/71776532/215695593-4815f6f0-9f79-450c-b64a-453d6dd7002b.png" />| <img width = 250 src = "https://user-images.githubusercontent.com/71776532/215695687-e8772404-82e9-4252-991c-0d69e7c2bf58.gif" />|<img width = 250 src = "https://user-images.githubusercontent.com/71776532/215695705-a90af1c7-0f34-46d4-a1df-ce271410e092.gif" />|
- 제일 좋은 건 서버에 공지를 등록하는 거
> [Feature] 추천피드 예외처리

- burstcamp/burstcamp/Data/Repositories/UserRepository/DefaultUserRepository.swift
- burstcamp/burstcamp/Domain/Model/User/User.swift
- burstcamp/burstcamp/Domain/UseCase/Auth/SignUp/DefaultSignUpUseCase.swift
- burstcamp/burstcamp/Domain/UseCase/Tab/MyPage/DefaultMyPageUseCase.swift
- burstcamp/burstcamp/Domain/UseCase/Tab/MyPage/MyPageEdit/DefaultMyPageEditUseCase.swift
- burstcamp/burstcamp/Domain/UseCase/Tab/MyPage/MyPageUseCase.swift
- burstcamp/burstcamp/Presentation/Auth/LogIn/ViewModel/LogInViewModel.swift
- burstcamp/burstcamp/Presentation/Coordinator/App/AppCoordinator.swift
- burstcamp/burstcamp/Presentation/Tab/MyPage/Edit/View/MyPageEditView.swift
- burstcamp/burstcamp/Presentation/Tab/MyPage/MyPage/ViewController/MyPageViewController.swift
- burstcamp/burstcamp/Presentation/Tab/MyPage/MyPage/ViewModel/MyPageViewModel.swift
- burstcamp/burstcamp/Service/Firebase/Model/UserAPIModel.swift
- burstcamp/burstcamp/Util/Extension/Type/Date+FormatString.swift
- close #275  
- 유저 정보 수정 횟수를 한 달에 1회로 제한했습니다.
- 유저 Model에 updateDate를 추가했습니다.
- 가입시 1970년 1월 1일로 설정됩니다. -> 최초 1회 수정 가능
- 30일을 기준으로 했습니다.
- 1월 1일 -> 1월 31일 true
- 1월 2일 -> 1월 31일 false, 2월 1일 true 
-  날짜에 맞추기 위해 뒤에 시간을 잘라줬습니다. 2023-01-01-23:00:00 -> 2023-01-01  
시간이 남아있으면 1월 1일 오후 11시에 업데이트를 하면 1월 30일 오후 11시부터 업데이트가 가능합니다.
formatter를 통해 시간을 짤라 날짜로만 계산합니다.  
이를 통해 1월 1일에 업데이트를 했으면 1월 31일에 업데이트가 가능합니다.
- Date extension에 30일이 지났는지 확인하는 함수를 구현했습니다.
- 유저가 업데이트시 updateDate도 갱신됩니다.
- MyPageEditView에 안내 문구를 추가했습니다.
- 30일이 안 지났으면 Alert으로 다음 수정날짜를 알려줍니다.
|MyPageEdit View에 안내 |업데이트 불가 안내 Alert|
|:---:|:---:|
|<img width = 250 src = "https://user-images.githubusercontent.com/71776532/215786532-ea156cb9-7c55-4557-816b-90f876d72759.png" />|<img width = 250 src = …
> Feature/유저 업데이트날짜

- burstcamp/burstcamp/Data/Local/FeedMockUpDatasource.swift
- burstcamp/burstcamp/Domain/UseCase/Tab/Home/DefaultHomeUseCase.swift
- burstcamp/burstcamp/Presentation/Tab/Home/View/HomeView.swift
- burstcamp/burstcamp/Presentation/Tab/Home/ViewController/HomeViewController.swift
- close #315 
- 기본적으로 목업 피드 1개 유지 -> 공지용
- else 문 처리를 잘못해 목업피드가 추가로 생기는 에러 수정
- 기존에 추천 피드 3개를 기준으로 스크롤 뷰 로직을 설계해둠 -> 3개 이상일 때 대응할 수 있도록 수정
- 서버에 추천피드가 없더라도 프론트에서 최소 3개의 목업 피드를 만들기때문에 무한 스크롤 대응 가능
> [Fix] 추천피드 에러

- burstcamp/burstcamp/Presentation/Auth/LogIn/View/LogInView.swift
- burstcamp/burstcamp/Presentation/Auth/LogIn/ViewController/LogInViewController.swift
- burstcamp/burstcamp/Presentation/Auth/SignUp/Blog/SignUpBlogView.swift
- burstcamp/burstcamp/Presentation/Auth/SignUp/Blog/SignUpBlogViewController.swift
- burstcamp/burstcamp/Presentation/Coordinator/App/AppCoordinator.swift
- burstcamp/burstcamp/Presentation/Coordinator/Auth/AuthCoordinator.swift
- burstcamp/burstcamp/Presentation/Tab/Home/ViewController/HomeViewController.swift
- burstcamp/burstcamp/Presentation/Tab/MyPage/MyPage/View/MyPageView.swift
- burstcamp/burstcamp/Presentation/Tab/MyPage/MyPage/ViewController/MyPageViewController.swift
- burstcamp/burstcamp/Service/Firebase/Firestore/BCFirestoreUserListener.swift
- burstcamp/burstcamp/Util/Extension/UI/ViewController/UIViewController+.swift
- close #317 
- 기존에 각 ViewController에서 관리했던 indicator 한 번에 관리
- UIViewController+.swift 파일에 구현했습니다.
- `showAnimatedActivityIndicatorView(description: String = "")`를 사용해 indicator를 보여줍니다.
- `hideAnimatedActivityIndicatorView()`를 사용해 indicator를 멈춥니다.
- `updateActivityOverlayDescriptionLabel(_ text: String)`를 사용해 중간에 text를 업데이트 할 수 있습니다.
| 라이트 모드 | 다크 모드 |
| :---:|:---:|
|<img witdh = 300 src = "https://user-images.githubusercontent.com/71776532/215953503-04870e13-1c4e-491e-9390-5f64ff9b5068.gif" /> |<img witdh = 300 src = "https://user-images.githubusercontent.com/71776532/215953479-9ae15571-3481-49a9-bbaf-1a07efc60d71.gif" />| 
- 일정 응답 시간이 지나면 자동으로 indicator가 꺼지고 Alert을 띄워줘야할 듯
> [Feature] UIViewController extension에 indicator view 설정

- burstcamp/burstcamp/App/AppDelegate.swift
- burstcamp/burstcamp/Presentation/Auth/LogIn/View/LogInView.swift
- burstcamp/burstcamp/Presentation/Common/View/Button/AuthButton.swift
- burstcamp/burstcamp/Service/Firebase/Auth/BCFirebaseAuthService.swift
- close #318 
- SFSymbols 버전 지원에 따른 오류
- iOS 15.0에 대한 분기 처리
- iOS 16.0 이상에서도 이상 없음 확인
| iPhone 13 pro iOS 15.0 수정 이전 | iPhone 13 pro iOS 15.0 수정 이후 | iPhone 14 pro max iOS 16.2 수정 이후 |
| :---:|:---:|:---:|
|<img witdh = 250 src = "https://user-images.githubusercontent.com/71776532/215956543-f5fe7d0f-c07a-4ec2-aff4-b8065cca9f57.png" /> |<img witdh = 250 src = "https://user-images.githubusercontent.com/71776532/215956550-f95c71d3-5b51-438a-a5db-8a7f3684aaca.png" />| <img witdh = 250 src = "https://user-images.githubusercontent.com/71776532/215956540-b8e686f6-735a-417a-8f2e-e782f01df56d.png" />|
- SFSymbols 사용할 때 버전 확인을 생활화합시다.
> [Fix] iOS 15.0 에서 애플 로그인 - apple image 안 보이던 오류 수정

- burstcamp/burstcamp/Domain/UseCase/Tab/MyPage/DefaultMyPageUseCase.swift
- burstcamp/burstcamp/Presentation/Tab/MyPage/MyPage/ViewController/MyPageViewController.swift
- close #321 
- 기존에 깃헙 프로필이미지를 쓰는 경우, Stroage에 이미지가 없는데 삭제 요청을 하게 되서 에러 메시지가 뜸
- `!profileImageURL.hasPrefix("https://github.com/")` 이면 요청을 하지 않도록 수정 
- 에러 코드 응답을 따로 처리할 까 했는데, 그러면 실제로 데이터가 없을 때 에러를 발생 못 시킨다고 판단해 URL 여부에 따라 요청을 처리했습니다.
> [fix] profileImage가 삭제시 에러 처리

- Firebase-Functions/functions/service/firestoreManager.js
- close #327 
- 일주일에 한 번 추천피드를 업데이트 합니다
- 로직
- 기존 추천피드를 삭제합니다.
- 전체 피드의 FeedUUID를 가져옵니다.
- 각 피드의 최근 일주일 간 ScrapCount를 가져옵니다.
- scrapCount top3를 정합니다. 이 때 count가 0 이면 포함하지 않습니다. -> 추천피드가 0~3개가 됩니다.
- scarpCount top3 피드를 일반 피드에서 호출해, 추천 피드에 저장합니다.
- 정상 작동 확인했습니다.
- 상세 로직은 주석 달아놨으니 확인해주시면 됩니다.
> [Feature] 클라우드 함수에서 추천 피드 설정

- burstcamp/burstcamp/Domain/UseCase/Tab/Home/DefaultHomeUseCase.swift
- burstcamp/burstcamp/Presentation/Common/View/NormalFeedCell/Main/NormalFeedCellMain.swift
- burstcamp/burstcamp/Presentation/Common/View/NormalFeedCell/NormalFeedCell.swift
- burstcamp/burstcamp/Presentation/Common/View/RecommendCell/RecommendFeedCell.swift
- burstcamp/burstcamp/Presentation/Common/View/RecommendCell/RecommendFeedUserView.swift
- close #336
- `setImage` 위치를 수정했습니다.
- 노말 피드 & 추천피드 prepare For Reuse에서 피드를 초기화 해줍니다.
- 추천피드 개수를 수정했습니다. 4 -> 3
> [Fix] 노말 피드 이미지 에러

- Firebase-Functions/functions/index.js
- Firebase-Functions/functions/service/apnsManager.js
- burstcamp/burstcamp/Data/Repositories/FeedRepository/DefaultFeedRepository.swift
- burstcamp/burstcamp/Data/Repositories/FeedRepository/MockUpFeedRepository.swift
- burstcamp/burstcamp/Domain/Interfaces/FeedRepository/FeedRepository.swift
- burstcamp/burstcamp/Domain/UseCase/Tab/Detail/DefaultFeedDetailUseCase.swift
- burstcamp/burstcamp/Domain/UseCase/Tab/Detail/FeedDetailUseCase.swift
- burstcamp/burstcamp/Presentation/Tab/Detail/ViewController/FeedDetailViewController.swift
- burstcamp/burstcamp/Presentation/Tab/Detail/ViewModel/FeedDetailViewModel.swift
- close #322 
- 기존에 리팩토링하면서 제거했던 딥링크를 복구했습니다.
- function함수에 소소한 수정이 있습니다.
- 기존 : feedUUID로  feed 호출 -> writer 호출 -> feed + writer 보냄
- 수정 후 : feeUUID로 feed 호출 -> feed에 writer 정보가 있으므로 그냥 보냄
- shell에서 `testMessaging()` 을 통해 바로 알람 확인 가능
- 현재 ViewController에서 언래핑 시 예외처리가 필요합니다.
- FeedDetail ViewModel에서 CurrentValueSubject를 사용해 Feed = nil로 초기값이 설정됩니다.
- 딥링크로 접근시 초기값 nil이 방출되고, feedUUID로 호출한 두 번째 Feed가 방출됩니다.
- 이에 따라 viewController에서 언래핑시 에러가 발생합니다. 우선은 nil인 경우 그냥 return으로 처리했습니다.
- 동작에는 이상이 없지만, 언래핑 과정에 따른 예외처리가 없어서 아쉽네요.
> [Feature] 피드 디테일 알람 시 deep link

- Firebase-Functions/functions/index.js
- Firebase-Functions/functions/service/firestoreManager.js
- burstcamp/burstcamp/Data/Repositories/UserRepository/DefaultUserRepository.swift
- burstcamp/burstcamp/Domain/Interfaces/UserRepository/UserRepository.swift
- burstcamp/burstcamp/Domain/UseCase/Auth/SignUp/DefaultSignUpUseCase.swift
- burstcamp/burstcamp/Presentation/Auth/SignUp/Blog/SignUpBlogViewController.swift
- burstcamp/burstcamp/Presentation/Auth/SignUp/Blog/SignUpBlogViewModel.swift
- burstcamp/burstcamp/Presentation/Auth/SignUp/CamperID/SignUpCamperIDViewController.swift
- burstcamp/burstcamp/Presentation/Tab/MyPage/Edit/View/MyPageEditView.swift
- burstcamp/burstcamp/Util/Extension/Combine/UIControl+Combine.swift
- modules/BCFirebase/BCFirebase/FireFunction/BCFirebaseFunctionService.swift
- modules/BCFirebase/BCFirebase/FireStorage/FireStorageError.swift
- close #247 
- 블로그가 있는 유저 회원 가입시 , DB 업데이트를 위한 함수를 구현했습니다. 하지만 현재 실행하지는 않습니다.
- 함수 구현을 통해 확인을 했고 Deploy까지 완료했습니다. 하지만 시간이 10초 넘게 걸리는 등 평균적으로 너무 긴 로딩 시간을 유저에게 보여줍니다. 이에 따라 스케줄러에 따른 DB 업데이트를 기다리려고 합니다.
- 회원 가입 버튼 누르면 키보드가 사라지도록 했습니다.
- textField + Combine publisher가 2종류 입니다.
- `textChangedPublisher` :  글자가 바뀔 때마다 publish
-  `textEditingEndPublisher` : textField에서 focus out 되면 publish
너무 오랜 시간이 걸려 유저 UX를 해침
> [Fix] 유저 회원가입시 DB 업데이트

- burstcamp/burstcamp/Presentation/Tab/MyPage/MyPage/ViewController/MyPageViewController.swift
- 애플 회원 탈퇴시 indicator가 사라지지 않는 에러를 수정했습니다.
- 기존에 coordinator - `moveToAuthFlow`로 이동하고 나서 hideIndicator를 호출해 indicator가 사라지지 않았습니다.
- 함수 호출 위치를 수정했습니다.
> fix: Indicator 위치 수정

- Firebase-Functions/functions/service/firestoreManager.js
- burstcamp/burstcamp/Domain/UseCase/Tab/MyPage/DefaultMyPageUseCase.swift
- 기존에 탈퇴시 scrapCount - 1이 안되던 걸 수정했습니다.
- remove UserListener 이후에 서버의 UserData를 삭제하도록 순서를 조정했습니다.
- 기존에 UserData를 삭제하고 remove UserListener를 진행하느라, error Alert이 떴습니다. 이를 수정하기 위해 위치를 조정했습니다.
> [fix] 탈퇴시 scrapCount 조정 & removeUserListener
